package base

type (
	ArkEntityEvent uint32
)

const (
	ENTITY_EVT_NONE ArkEntityEvent = iota
	ENTITY_EVT_DESTROY
	ENTITY_EVT_PRE_DESTROY
	ENTITY_EVT_PRE_LOAD_DATA
	ENTITY_EVT_LOAD_DATA
	ENTITY_EVT_PRE_EFFECT_DATA
	ENTITY_EVT_EFFECT_DATA
	ENTITY_EVT_POST_EFFECT_DATA
	ENTITY_EVT_DATA_FINISHED
	ENTITY_EVT_ALL_FINISHED // Call it by yourself when create entity finished
)
